import Head from 'next/head'

import styles from '../styles/Home.module.css'

import Nav from '../components/nav/Nav'
import AddPost from '../components/addPost/AddPost'
import CardItem from '../components/item/CardItem';
import auth from '../hooks/auth';
import { useRouter } from 'next/router';
import Remove from '../components/remove/Remove';
import { useEffect } from 'react';
import Registerpage from './registerpage';


export default function Home() {
    const nav = useRouter();
    
    const {isAuth} = auth();
  return isAuth?(
    <div className={styles.container}>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <Nav/>  
       <CardItem/>
       <AddPost/>
       <Remove/>
     
    </div>
  ):<Registerpage/>
  
  
     
}
